image: nexus.eitccorp.com/ionic/ci-build:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GOPRIVATE: gitlab.eitccorp.com/*
  GOPATH: ${CI_PROJECT_DIR}/.cache

.build:
  artifacts:
    paths:
      - dist/
    expire_in: 90 min

.git:
  before_script:
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - git config --global credential.helper store
    - git config --global user.name ${GITLAB_USER_LOGIN}
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}" > ~/.git-credentials

.git-shallow:
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0

.cache:
  extends: [ .git ]
  cache:
    paths:
      - .cache

stages:
  - prepare
  - test
  - build
  - check
  - release

prepare:
  stage: prepare
  extends: .cache
  script:
    - mkdir -p .cache
    - go mod tidy

test:
  stage: test
  extends: .cache
  script:
    - mage test

lint:
  stage: test
  extends: .cache
  script:
    - mage lint
  allow_failure: true

build:
  stage: build
  extends: [ .cache, .git-shallow ]
  needs: []
  script:
    - mage build
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success

release:
  image: nexus.eitccorp.com/ionic/ci-build:docker
  services:
    - name: nexus.eitccorp.com/gitlab/docker:20.10.20-dind
      alias: docker
  stage: release
  extends: [ .cache, .git-shallow ]
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - aws ecr get-login-password --region us-gov-west-1 | docker login --username AWS --password-stdin $RADMF_DEV_REGISTRY
    - mage release
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
