# Make sure to check the documentation at https://goreleaser.com
project_name: cnpg-plugin-s3-backup

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: cnpg-plugin-s3-backup
    main: ./cmd/s3-backup
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=gitlab.eitccorp.com/*
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -extldflags='-static'

dockers:
  - id: cnpg-plugin-s3-backup
    ids:
      - cnpg-plugin-s3-backup
    image_templates:
      - "664358975573.dkr.ecr.us-gov-west-1.amazonaws.com/ionic/cnpg-plugin-s3-backup:latest"
      - "664358975573.dkr.ecr.us-gov-west-1.amazonaws.com/ionic/cnpg-plugin-s3-backup:{{ .Tag }}"
      - "registry.eitccorp.com/ionic/infra/cnpg-plugin-s3-backup:latest"
      - "registry.eitccorp.com/ionic/infra/cnpg-plugin-s3-backup:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

archives:
  - id: cnpg-plugin-s3-backup
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

gitlab_urls:
  api: '{{ .Env.CI_API_V4_URL }}'
  download: '{{ .Env.CI_SERVER_URL }}'
  skip_tls_verify: false
  use_package_registry: true

release:
  gitlab:
    owner: "ionic/infra"
    name: "cnpg-plugin-s3-backup"
  disable: false

publishers:
  - name: nexus
    cmd: >-
      curl -k -u "{{ .Env.DEPLOY_USER }}:{{ .Env.DEPLOY_TOKEN }}"
        -X POST
        -H "Accept: application/json"
        -H "Content-Type: multipart/form-data"
        "https://nexus.eitccorp.com/service/rest/v1/components?repository=ionic-releases"
        -F "maven2.groupId=ionic"
        -F "maven2.artifactId={{ tolower .ProjectName }}"
        -F "maven2.version={{ .Version }}"
        -F "maven2.asset1=@{{ .ArtifactName }}"
        -F "maven2.asset1.extension=tar.gz"
    dir: "{{ dir .ArtifactPath }}"

